version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    allow:
      - dependency-type: "direct"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "eslint*"
      rollup:
        patterns:
          - "@rollup/plugin-typescript"
          - "rollup"
          - "rollup-plugin-dts"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
