name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.nix'
      - '.all-contributorsrc'
      - '.vscode/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'compose.yml'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.nix'
      - '.all-contributorsrc'
      - '.vscode/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo under GH workspace
      uses: actions/checkout@v4

    - name: Use nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'

    - name: Install deps without updating package-lock.json
      run: npm ci

    - name: Run the CI build
      run: npm run ci

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
